# Copyright (c) 2020 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (Release, FetchContent)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: stellargroup/build_env:10

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: |
          cmake \
              tests/unit/build/fetchcontent \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DPIKA_REPOSITORY="file:////$(pwd)" \
              -DPIKA_TAG="$GITHUB_SHA" \
              -DPIKA_WITH_UNITY_BUILD=ON \
              -DPIKA_WITH_MALLOC=system \
              -DPIKA_WITH_EXAMPLES=ON \
              -DPIKA_WITH_TESTS=OFF \
              -DPIKA_WITH_CHECK_MODULE_DEPENDENCIES=On \
              -DPIKA_WITH_APEX=ON

    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target examples
